# Generated by Django 4.2.11 on 2024-04-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Doc", "0007_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="task",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
