# Generated by Django 4.2.11 on 2024-04-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Doc", "0008_rename_task_task_description_remove_task_timestamp_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogoImage",
        ),
        migrations.DeleteModel(
            name="PDFFile",
        ),
    ]
